[package]
name = "primerug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rug = "1.19.0"
rand = "0.8.5"
clap = { version = "4.1.4", features = ["derive"] }
bit-vec = "0.6.3"
pbr = "1.0.4"
indicatif = "0.17.3"
